import streamlit as st
#from Appcall.py import generate_response  # Import your function from function.py

#----------BUILDING the APP.py----------------------------#

# Set Streamlit app title with emojis of a parrot and a chain
st.title("RBC Transition  AI Assistant ")

# Define the colors for the RBC Bank Canada color palette
rbc_canada_palette = {
    "primary": "#003366",      # RBC Blue
    "secondary": "#FF7F00",    # RBC Orange
    "background": "#FFFFFF",   # White
    "text": "#333333",         # Dark Gray
}
# Set page background color and text color using RBC Bank Canada color palette
st.markdown(
    f"""
    <style>
    body {{
        background-color: {rbc_canada_palette["background"]};
        color: {rbc_canada_palette["text"]};
    }}
    </style>
    """,
    unsafe_allow_html=True,
)

# Get user input from text area
user_input = st.text_area("Please enter your query on transition of your HSBC accounts to RBC:")

# Check if the user has entered any input
if user_input:
    # Process user input and get the model's output
    model_output = user_input #generate_response(user_input)

    # Display the output in formatted text format
    st.markdown(
        f"""
        <div style='background-color: {rbc_canada_palette["secondary"]}; padding: 10px;'>
            <p style='color: {rbc_canada_palette["primary"]}; font-size: 18px;'>
                {model_output}
            </p>
        </div>
        """,
        unsafe_allow_html=True,
    )

# Add the disclaimer at the bottom of the page
st.markdown(
    """
    #### Disclaimer:
    The information provided by this application is for educational purposes only and should not be considered
     as legal advice. All answers to the queries are generated by an AI model and may not be entirely accurate or 
     up-to-date. Please speak to a relationship manager for any specific details relating to your account before making any changes.
    """,
    unsafe_allow_html=True,
)
